name: pay_me
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  dio: ^4.0.0
  mocktail: ^0.1.1
  lottie: ^1.3.0
  flutter_slider_indicator: ^1.0.0
  http: ^0.13.4
  dartz: ^0.10.1
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/landing_page_animation.json
    - assets/1024.png
 