// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUCHZVUaZDXJXgBqqCRNzRum9P04A_DU',
    appId: '1:658496655188:web:f6fdca7ae70cb958b942c1',
    messagingSenderId: '658496655188',
    projectId: 'payflex-6f1b3',
    authDomain: 'payflex-6f1b3.firebaseapp.com',
    storageBucket: 'payflex-6f1b3.appspot.com',
    measurementId: 'G-T3C1H2SJ24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2etwdLZjXOYE3SZ6auhChB0zQvXDDz2c',
    appId: '1:658496655188:android:72401c1e011f6970b942c1',
    messagingSenderId: '658496655188',
    projectId: 'payflex-6f1b3',
    storageBucket: 'payflex-6f1b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQrbvNt-eVoOUe3kRefydoBklrF8Jk9Ns',
    appId: '1:658496655188:ios:4124bf3120f7cbe0b942c1',
    messagingSenderId: '658496655188',
    projectId: 'payflex-6f1b3',
    storageBucket: 'payflex-6f1b3.appspot.com',
    iosBundleId: 'com.example.payMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQrbvNt-eVoOUe3kRefydoBklrF8Jk9Ns',
    appId: '1:658496655188:ios:4124bf3120f7cbe0b942c1',
    messagingSenderId: '658496655188',
    projectId: 'payflex-6f1b3',
    storageBucket: 'payflex-6f1b3.appspot.com',
    iosBundleId: 'com.example.payMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqUCHZVUaZDXJXgBqqCRNzRum9P04A_DU',
    appId: '1:658496655188:web:c334584009c4b8e8b942c1',
    messagingSenderId: '658496655188',
    projectId: 'payflex-6f1b3',
    authDomain: 'payflex-6f1b3.firebaseapp.com',
    storageBucket: 'payflex-6f1b3.appspot.com',
    measurementId: 'G-0X6ZSV50YE',
  );
}
